export * from "./header/index";
export * from "./sectionHome/index";
export * from "./sectionServices/index";
export * from "./serviceCard/index";
export * from "./sectionAboutUs/index";
export * from "./sectionDepositions/index";
export * from "./commentCard/index";
export * from "./footer/index";
export * from "./footerLinks/index";
export * from "./googleButton/index";
export * from './facebookButton/index';
export * from './appleButton/index';
export * from './doctorCard/index'